import Head from "next/head";
import Layout from "~/components/Layout";
import type { NextPageWithLayout } from "./_app";
import type { ReactElement } from "react";
import AboutUsSection from "~/components/home/AboutUsSection";
import FAQSection from "~/components/home/FAQSection";
import PropertiesSection from "~/components/home/PropertiesSection";
import TestimonialsSection from "~/components/home/TestimonialsSection";
import AmenitiesSection from "~/components/home/AmenitiesSections";
import HeroSection from "~/components/home/HeroSection";
import SupportSection from "~/components/home/SupportSection";
import BlogSection from "~/components/home/BlogSection";

const HomePage: NextPageWithLayout = () => {
  
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto px-8 lg:px-12">
        <HeroSection />
        <AmenitiesSection />
        <AboutUsSection />
        <TestimonialsSection />
        <PropertiesSection />
        <BlogSection />
        <FAQSection />
        <SupportSection />
      </main>
    </>
  );
};

export default HomePage;

HomePage.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};



